version: '3'

services:

  server:
    image: kodear/php7.2-apache
    volumes:
      - ./:/var/www/html
      - ./docker/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache2/ports.conf:/etc/apache2/ports.conf
      - ./docker/apache2/conf-enabled/docker-php.conf:/etc/apache2/conf-enabled/docker-php.conf
      - ./docker/apache2/mods-enabled/rewrite.load:/etc/apache2/mods-enabled/rewrite.load
    ports:
      - 8888:80
    links:
      - db
    tty: true
    container_name: books-repository-server

  db:
    container_name: books-repository-db
    image: mysql:5.7
    ports:
      - 33065:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=books_repository"